// Emulates the process of sending out requests to server like a client.

### TEST GET / 
GET http://localhost:3000

### TEST GET /dashboard
GET http://localhost:3000/dashboard


### DATA ENDPOINT
GET http://localhost:3000/api/data

### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name": "GIBBerish"
}

### DATA ENDPOINT FOR DELETING A USER
DELETE http://localhost:3000/api/data